"""Add name indexes

Revision ID: 282819f073d6
Revises: 2911fee4324e
Create Date: 2025-10-18 22:04:03.948620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '282819f073d6'
down_revision: Union[str, Sequence[str], None] = '2911fee4324e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_accumulator_name'), 'accumulator', type_='unique')
    op.create_index(op.f('ix_accumulator_name'), 'accumulator', ['name'], unique=True)
    op.drop_constraint(op.f('uq_device_name'), 'device', type_='unique')
    op.create_index(op.f('ix_device_name'), 'device', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_name'), table_name='device')
    op.create_unique_constraint(op.f('uq_device_name'), 'device', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_accumulator_name'), table_name='accumulator')
    op.create_unique_constraint(op.f('uq_accumulator_name'), 'accumulator', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
