"""Init db

Revision ID: 2952afe0d642
Revises: 
Create Date: 2025-10-19 12:13:18.439594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2952afe0d642'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('firmware_ver', sa.String(), nullable=False),
    sa.Column('is_on', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device'))
    )
    op.create_index(op.f('ix_device_name'), 'device', ['name'], unique=True)
    op.create_table('accumulator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rated_voltage', sa.Numeric(), nullable=False),
    sa.Column('residual_capacity', sa.Numeric(), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('rated_voltage >= 0', name=op.f('ck_accumulator_positive_volume')),
    sa.CheckConstraint('residual_capacity >= 0', name=op.f('ck_accumulator_positive_capacity')),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], name=op.f('fk_accumulator_device_id_device'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accumulator'))
    )
    op.create_index(op.f('ix_accumulator_device_id'), 'accumulator', ['device_id'], unique=False)
    op.create_index(op.f('ix_accumulator_name'), 'accumulator', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accumulator_name'), table_name='accumulator')
    op.drop_index(op.f('ix_accumulator_device_id'), table_name='accumulator')
    op.drop_table('accumulator')
    op.drop_index(op.f('ix_device_name'), table_name='device')
    op.drop_table('device')
    # ### end Alembic commands ###
