"""Add accumulator.lifespan field

Revision ID: 2f76bf7ce281
Revises: 282819f073d6
Create Date: 2025-10-19 05:06:35.939930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f76bf7ce281'
down_revision: Union[str, Sequence[str], None] = '282819f073d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accumulator', sa.Column('lifespan', sa.Interval(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accumulator', 'lifespan')
    # ### end Alembic commands ###
